### Importing the required libraries

In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
import joblib as jl

### Loading the excel dataset into pandas

In [9]:
mdf = pd.read_excel("/Users/samhithkonidena/My Data Journey/Data Job Prep/Portfolio/Analysis/Titanic_Analysis/Cleaned_Data/Titanic_Cleaned_Data.xlsx")
mdf.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,cabin_known,age_category,ship_class,survivor?
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,Youth,Third Class,No
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,Adult,First Class,Yes
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,Adult,Third Class,Yes
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,Adult,First Class,Yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,Adult,Third Class,No

#### Deriving the `family_size` and `is_alone` features/columns

In [10]:
mdf["family_size"] = mdf["sibsp"] + mdf["parch"] + 1
mdf["is_alone"] = mdf["family_size"] == 1
mdf.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,cabin_known,age_category,ship_class,survivor?,family_size,is_alone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,Youth,Third Class,No,2,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,Adult,First Class,Yes,2,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,Adult,Third Class,Yes,1,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,Adult,First Class,Yes,2,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,Adult,Third Class,No,1,True

### Defining the 'X' and 'Y' feature datasets for the model to train on

In [11]:
X = mdf[["pclass", "sex", "age", "embarked", "family_size", "is_alone"]]
y = mdf["survived"]

X.head()
X.shape
y.head()
y.shape

(891,)

### Splitting both datasets for the model to train and test on

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

### Checking the target dataset distribution

In [13]:
y_train.value_counts(normalize=True)
y_test.value_counts(normalize=True)
X.head()

   pclass     sex   age embarked  family_size  is_alone
0       3    male  22.0        S            2     False
1       1  female  38.0        C            2     False
2       3  female  26.0        S            1      True
3       1  female  35.0        S            2     False
4       3    male  35.0        S            1      True

### Creating feature lists for encoding/preprocessing

In [14]:
num_features = ["pclass", "age", "family_size", "is_alone"]
cat_features = ["sex", "embarked"]

### Creating the two column transformers for processing two kinds of features

In [15]:
num_transformer = StandardScaler()
cat_transformer = OneHotEncoder(handle_unknown='ignore')

### Applying the transformers on the features

In [16]:
preprocessor = ColumnTransformer([
    ("numbers", num_transformer, num_features),
    ("categories", cat_transformer, cat_features)
])

### Introducing/defining the model

In [17]:
model = LogisticRegression()

### Creating the model processing pipeline

In [18]:
pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

### Training the model

In [19]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numbers', StandardScaler(),
                                                  ['pclass', 'age',
                                                   'family_size', 'is_alone']),
                                                 ('categories',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['sex', 'embarked'])])),
                ('model', LogisticRegression())])

#### Generating the `X_test` prediction and probability

In [20]:
y_pred = pipeline.predict(X_test)
print(y_pred)

[0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 1 0 1 1 0 0 1 1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 1 1 0 0 0 1 0 1 1
 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0
 1 1 0 0 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 1 1 0 0 1 0 1 0 0 1 0]

In [21]:
y_pred_proba = pipeline.predict_proba(X_test)
print(y_pred_proba)

[[0.90239652 0.09760348]
 [0.93486827 0.06513173]
 [0.85993144 0.14006856]
 [0.9451568  0.0548432 ]
 [0.23656938 0.76343062]
 [0.44878793 0.55121207]
 [0.26880547 0.73119453]
 [0.68801535 0.31198465]
 [0.63360728 0.36639272]
 [0.76549316 0.23450684]
 [0.84870179 0.15129821]
 [0.87337009 0.12662991]
 [0.4462763  0.5537237 ]
 [0.7316492  0.2683508 ]
 [0.66596941 0.33403059]
 [0.8340437  0.1659563 ]
 [0.59380035 0.40619965]
 [0.91663008 0.08336992]
 [0.8802155  0.1197845 ]
 [0.25465184 0.74534816]
 [0.91663008 0.08336992]
 [0.19303853 0.80696147]
 [0.92206058 0.07793942]
 [0.51264034 0.48735966]
 [0.91938704 0.08061296]
 [0.05127962 0.94872038]
 [0.84870179 0.15129821]
 [0.64134989 0.35865011]
 [0.88806629 0.11193371]
 [0.88437289 0.11562711]
 [0.93196063 0.06803937]
 [0.08535195 0.91464805]
 [0.88160919 0.11839081]
 [0.90783838 0.09216162]
 [0.84219769 0.15780231]
 [0.81630561 0.18369439]
 [0.84219769 0.15780231]
 [0.69390526 0.30609474]
 [0.84870179 0.15129821]
 [0.15619647 0.84380353]
 [0.84288977 0.15711023]
 [0.04332315 0.95667685]
 [0.88240416 0.11759584]
 [0.15489861 0.84510139]
 [0.26166688 0.73833312]
 [0.89482453 0.10517547]
 [0.91663008 0.08336992]
 [0.48524327 0.51475673]
 [0.21854175 0.78145825]
 [0.13085267 0.86914733]
 [0.09750751 0.90249249]
 [0.45534523 0.54465477]
 [0.2990014  0.7009986 ]
 [0.78292109 0.21707891]
 [0.44491065 0.55508935]
 [0.9108578  0.0891422 ]
 [0.88873589 0.11126411]
 [0.60457017 0.39542983]
 [0.39281012 0.60718988]
 [0.59578022 0.40421978]
 [0.2970203  0.7029797 ]
 [0.30057456 0.69942544]
 [0.87629913 0.12370087]
 [0.87458639 0.12541361]
 [0.48962553 0.51037447]
 [0.36073867 0.63926133]
 [0.04348757 0.95651243]
 [0.92960077 0.07039923]
 [0.79850193 0.20149807]
 [0.75698971 0.24301029]
 [0.19064637 0.80935363]
 [0.88437289 0.11562711]
 [0.29342482 0.70657518]
 [0.05478673 0.94521327]
 [0.81243757 0.18756243]
 [0.94419962 0.05580038]
 [0.93424699 0.06575301]
 [0.87739608 0.12260392]
 [0.8943848  0.1056152 ]
 [0.49411944 0.50588056]
 [0.9450848  0.0549152 ]
 [0.89165617 0.10834383]
 [0.86227899 0.13772101]
 [0.9108578  0.0891422 ]
 [0.24815501 0.75184499]
 [0.62432938 0.37567062]
 [0.89677756 0.10322244]
 [0.37786518 0.62213482]
 [0.46965728 0.53034272]
 [0.04040779 0.95959221]
 [0.54193263 0.45806737]
 [0.54193263 0.45806737]
 [0.9260976  0.0739024 ]
 [0.91663008 0.08336992]
 [0.61569946 0.38430054]
 [0.21522014 0.78477986]
 [0.38039931 0.61960069]
 [0.84870179 0.15129821]
 [0.93424699 0.06575301]
 [0.90783838 0.09216162]
 [0.80433138 0.19566862]
 [0.15402887 0.84597113]
 [0.2990014  0.7009986 ]
 [0.07663215 0.92336785]
 [0.9108578  0.0891422 ]
 [0.54193263 0.45806737]
 [0.69913783 0.30086217]
 [0.91663008 0.08336992]
 [0.88772741 0.11227259]
 [0.51362512 0.48637488]
 [0.84870179 0.15129821]
 [0.99110073 0.00889927]
 [0.91378768 0.08621232]
 [0.7062842  0.2937158 ]
 [0.17955638 0.82044362]
 [0.84870179 0.15129821]
 [0.83529227 0.16470773]
 [0.87629913 0.12370087]
 [0.87340079 0.12659921]
 [0.80433138 0.19566862]
 [0.91663008 0.08336992]
 [0.27798933 0.72201067]
 [0.9518239  0.0481761 ]
 [0.56690859 0.43309141]
 [0.88402428 0.11597572]
 [0.90859261 0.09140739]
 [0.47133986 0.52866014]
 [0.46690241 0.53309759]
 [0.90629446 0.09370554]
 [0.53282625 0.46717375]
 [0.91663008 0.08336992]
 [0.91663008 0.08336992]
 [0.23656938 0.76343062]
 [0.84870179 0.15129821]
 [0.62794127 0.37205873]
 [0.89132683 0.10867317]
 [0.06566904 0.93433096]
 [0.84870179 0.15129821]
 [0.2990014  0.7009986 ]
 [0.91663008 0.08336992]
 [0.48962553 0.51037447]
 [0.86641981 0.13358019]
 [0.45299318 0.54700682]
 [0.54445328 0.45554672]
 [0.8326901  0.1673099 ]
 [0.72124942 0.27875058]
 [0.91663008 0.08336992]
 [0.70127025 0.29872975]
 [0.11308654 0.88691346]
 [0.1647333  0.8352667 ]
 [0.91378768 0.08621232]
 [0.80404601 0.19595399]
 [0.14931592 0.85068408]
 [0.20191546 0.79808454]
 [0.76081809 0.23918191]
 [0.36929309 0.63070691]
 [0.77663091 0.22336909]
 [0.87739608 0.12260392]
 [0.74573457 0.25426543]
 [0.21257906 0.78742094]
 [0.34882691 0.65117309]
 [0.12801579 0.87198421]
 [0.2990014  0.7009986 ]
 [0.1125312  0.8874688 ]
 [0.09339191 0.90660809]
 [0.41930639 0.58069361]
 [0.9233667  0.0766333 ]
 [0.70352066 0.29647934]
 [0.19150402 0.80849598]
 [0.34408455 0.65591545]
 [0.94835102 0.05164898]
 [0.88437289 0.11562711]
 [0.45145769 0.54854231]
 [0.80135323 0.19864677]
 [0.15146475 0.84853525]
 [0.89132683 0.10867317]
 [0.78292109 0.21707891]
 [0.1370742  0.8629258 ]
 [0.79671924 0.20328076]]

In [22]:
y_pred[:10]

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [23]:
y_pred_proba[:10]

array([[0.90239652, 0.09760348],
       [0.93486827, 0.06513173],
       [0.85993144, 0.14006856],
       [0.9451568 , 0.0548432 ],
       [0.23656938, 0.76343062],
       [0.44878793, 0.55121207],
       [0.26880547, 0.73119453],
       [0.68801535, 0.31198465],
       [0.63360728, 0.36639272],
       [0.76549316, 0.23450684]])

### Calculating model accuracy

In [24]:
accuracy = accuracy_score(y_test, y_pred)
print (accuracy*100)

79.3296089385475

### Calculating model confusion

In [25]:
confusion = confusion_matrix(y_test, y_pred)
print(confusion)

[[94 16]
 [21 48]]

### Calculating recall, precision, and f1 scores

In [26]:
recall = recall_score(y_test, y_pred)
print(recall*100)

69.56521739130434

In [27]:
precision = precision_score(y_test, y_pred)
print(precision*100)

75.0

In [28]:
f1 = f1_score(y_test, y_pred)
print(f1*100)

72.18045112781954

### Building the interactive predictive picker function

In [29]:
passenger = {
    "age":30,
    "sex":"male",
    "pclass":3,
    "embarked":"S",
    "sibsp":0,
    "parch":1
}

family_size = passenger["sibsp"] + passenger["parch"] + 1
is_alone = family_size == 1

In [30]:
X_sample = pd.DataFrame([{
    "age":passenger["age"],
    "sex":passenger["sex"],
    "pclass":passenger["pclass"],
    "embarked":passenger["embarked"],
    "family_size": family_size,
    "is_alone": is_alone
}])

X_sample

   age   sex  pclass embarked  family_size  is_alone
0   30  male       3        S            2     False

In [31]:
prediction = pipeline.predict(X_sample)
print(prediction)

[0]

In [32]:
probability = pipeline.predict_proba(X_sample)
print(probability*100)

[[89.57767459 10.42232541]]

In [33]:
def predict_survival(passenger_info):

    family_size = passenger_info["sibsp"] + passenger_info["parch"] + 1
    is_alone = family_size == 1

    X_passenger = pd.DataFrame([{
        "pclass": passenger_info["pclass"],
        "sex": passenger_info["sex"],
        "age": passenger_info["age"],
        "embarked": passenger_info["embarked"],
        "family_size": family_size,
        "is_alone": is_alone
    }])

    prediction = pipeline.predict(X_passenger)
    probability = pipeline.predict_proba(X_passenger)

    prediction = int(prediction[0])
    survival_probability = float(probability[0][1])

    result_text = "Survived" if prediction == 1 else "Didn't survive"
    survival_percentage = round(survival_probability * 100, 2)

    return survival_percentage, result_text

In [34]:
predict_survival(passenger)

(10.42, "Didn't survive")

### Exporting the model

In [35]:
jl.dump(pipeline, "/Users/samhithkonidena/My Data Journey/Data Job Prep/Portfolio/Analysis/Titanic_Analysis/Scripts/models/picker_pipeline.pkl")

['/Users/samhithkonidena/My Data Journey/Data Job Prep/Portfolio/Analysis/Titanic_Analysis/Scripts/models/picker_pipeline.pkl']